RF, Anti-CCP → impute + add _was_missing flag (their missingness was class-dependent)
Everything else (ESR, CRP, HLA-B27, ANA, Anti-Ro, Anti-La, Anti-dsDNA, Anti-Sm, C3, C4) → straight MICE, no flag needed

In [2]:
import pandas as pd
import numpy as np

df = pd.read_excel("../data/raw/dataset.xlsx")
df.shape

(12085, 15)

In [3]:
# add missing flags because we are adding aditional column of was this originally missing needed for rf
df['RF_was_missing'] = df['RF'].isna().astype(int)
df['Anti-CCP_was_missing'] = df['Anti-CCP'].isna().astype(int)

df[['RF', 'RF_was_missing', 'Anti-CCP', 'Anti-CCP_was_missing']].head(10)

     RF  RF_was_missing  Anti-CCP  Anti-CCP_was_missing
0  34.2               0      29.9                     0
1  35.5               0      28.9                     0
2  21.3               0      21.3                     0
3  26.0               0      39.0                     0
4  38.1               0      30.8                     0
5   NaN               1      37.3                     0
6  22.3               0       NaN                     1
7  31.8               0      38.1                     0
8  33.4               0       NaN                     1
9  37.4               0      25.0                     0

In [4]:
df['RF_was_missing'].sum(), df['RF'].isna().sum()

(np.int64(1329), np.int64(1329))

In [5]:
#MICE needs  umeric so first convert positive/negative to 1/0
binary_cols = ['HLA-B27', 'ANA', 'Anti-Ro', 'Anti-La', 'Anti-dsDNA', 'Anti-Sm']

for col in binary_cols:
    df[col] = df[col].map({'Positive': 1, 'Negative': 0})

df[binary_cols].head(10)

   HLA-B27  ANA  Anti-Ro  Anti-La  Anti-dsDNA  Anti-Sm
0      1.0  0.0      1.0      0.0         1.0      1.0
1      0.0  NaN      1.0      NaN         1.0      NaN
2      0.0  0.0      NaN      1.0         0.0      NaN
3      NaN  NaN      1.0      1.0         NaN      NaN
4      1.0  0.0      1.0      0.0         1.0      0.0
5      1.0  NaN      0.0      0.0         NaN      0.0
6      0.0  1.0      0.0      NaN         1.0      1.0
7      0.0  1.0      0.0      0.0         1.0      1.0
8      NaN  NaN      1.0      NaN         1.0      NaN
9      1.0  0.0      0.0      NaN         1.0      1.0

In [6]:
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})